### ISSUE TITLE
google experiment not working

### ISSUE THREAD

**Issue by LucasIsasmendi** [revolunet/angular-google-analytics#125]
After setup experiment id, the function createAnalyticsScriptTag() never is called, therefore the experiment never load.

Also is pending a function that retireves the experiment value:
variationNumber = cxApi.getChosenVariation();
https://developers.google.com/analytics/devguides/collection/analyticsjs/experiments#cxjs-getchosen

**Comment by justinsa** [comment]
@LucasIsasmendi - Did you add the Analytics service to at least a single run method as is described in the documentation? The service has to be instantiated at least once and that only happens if it is referenced by an `angular.run` method or a controller.

**Comment by LucasIsasmendi** [comment]
Thanks justinsa, I did the update and now that line of code runs, however, as per google docs, experiment call should return a variation number, where is that code? how can I get the callback from google to obtain the variation number?
An example from other script is:
angularLoad.loadScript('//www.google-analytics.com/cx/api.js?experiment=' + experimentId).then(function() {
                var choosenVar = cxApi.getChosenVariation()
                var chooseVar = cxApi.chooseVariation()
            })

**Comment by justinsa** [comment]
@LucasIsasmendi that isn't a callback from Google in the example you provide, but a thenable callback from a promise that happens to be for a script post-load. If you have Analytics in the angular run method then cxApi may already be available as a global by the time the method body executes. Ideally it will be but that depends on the script loading performed by the browser. For example, you may be able to do the following:

```js
angular.run(function (Analytics) {
  var choosenVar = cxApi.getChosenVariation();
  var chooseVar = cxApi.chooseVariation();
});
```

The above might also result in a race condition because it isn't guaranteed that the api.js script will have definitely been loaded by then.

**Comment by LucasIsasmendi** [comment]
Great!, it works within the run section as you mention.
Thanks!
