### ISSUE TITLE
Exclude url from tracking with ui-router

### ISSUE THREAD

**Issue by lyvyu** [revolunet/angular-google-analytics#178]
Hello,
i have a problem here, i am using this module with ui-router but i have one url not to be tracked because i send this manually with Analytics.trackPage('...').

The question is how can i get this done ?

Thanks in advance.

**Comment by lyvyu** [comment]
So guys ? anyone could help ?

**Comment by martyzz1** [comment]
I think you will have to use Analytics.trackPAge() on all pages... and wrap this call in an if not page_url = dont_track_url)

You could do this using a rootScope stateChangesuccess handler...

**Comment by lyvyu** [comment]
@martyzz1 
Yeah, thanks man, i've already did this:
`
      $rootScope.analyticsExceptionRoutes = [...];
      ...
      // check if need to track page
      if ($rootScope.analyticsExceptionRoutes.indexOf($location.path()) === -1) {
        Analytics.trackPage($location.path());
      }
`
but it thought that it might be another way to do this without writing any code of mine.
Any way, thaks dude for the answer!

**Comment by Toxantron** [comment]
For ngRoute I added support a while back to include such configurations into the route definition as you can see [here](https://github.com/revolunet/angular-google-analytics#set-route-tracking-behaviors). There was also the attempt to customize the behavior of route tracking with a new API in the future in #149.

However due to a shift in personal priorities my time for this project is down to almost zero. Maybe it is a starting point for you though.

**Comment by lyvyu** [comment]
@Toxantron well, ok...i think i'll give a try for this.
