### ISSUE TITLE
Add HTTPS in angular-google-analytics.js

### ISSUE THREAD

**Issue by wilsontamarozzi** [revolunet/angular-google-analytics#179]
Hello,

Excuse my English, I live in Brazil.

I'm developing an extension for Chrome and security policy it only accepts external links in **HTTPS**.

I had to modify the angular-google-analytics.js file the following lines:

**Line 442:** `scriptsource = ( 'https:' === document.location.protocol 'https: //': 'http: //' ') +' stats.g.doubleclick.net/dc.js';`

**To:** `scriptsource = ( 'https:' === document.location.protocol 'https: //': 'https: //' ') +' stats.g.doubleclick.net/dc.js';`

**Lines 444:** `scriptsource = ( 'https:' === document.location.protocol 'https: // ssl': 'http: // www' ') +' .google-analytics.com / ga.js';`

**To:** `scriptsource = ( 'https:' === document.location.protocol 'https: // ssl': 'https: // www' ') +' .google-analytics.com / ga.js';`

Link which explains best: http://stackoverflow.com/questions/12129077/content-security-policy-cannot-load-google-api-in-chrome-extension

**Comment by revolunet** [comment]
Hi, thanks for reporting

can you please tell what `document.location.protocol` value is in your extension ?

**Comment by wilsontamarozzi** [comment]
Hi,

I put to display in `console.log(document.location.protocol)` and my exit was: `chrome-extension:`

**Comment by justinsa** [comment]
So the fix is that ['https:', 'chrome-extension:'] === document.location.protocol. Seems like a reasonable time to abstract this to a function that returns an appropriate result based on whether it should serve HTTPS or HTTP.

Maybe something like:

```javascript
var _requiresSsl = function(protocol, secureValue, insecureValue) {
  var result = insecureValue;
  if ('https:' === protocol || 'chrome-extension:' === protocol) {
    result = secureValue;
  }
  return result;
}
```

The line on 442 can be changed to:

```javascript
scriptsource = that._requireSsl(document.location.protocol, 'https://', 'http://') + 'stats.g.doubleclick.net/dc.js';
```

and 444 can be changed to:

```javascript
scriptsource = that._requireSsl(document.location.protocol, 'https://ssl', 'http://www') + '.google-analytics.com/ga.js';
```

That will allow this to be updated fairly easy in the future should new extensions be required and as long as the resource only requires two choices, but so far we haven't seen more choices so no reason to over engineer just yet.

**Comment by justinsa** [comment]
Also, I might be able to write this and unit tests for it in the next week and get this shipped as a release.
