### ISSUE TITLE
CDN pointing to wrong version?

### ISSUE THREAD

**Issue by origooo** [revolunet/angular-google-analytics#228]
I'm using version 1.1.8 while developing, installed through bower.

When I deploy to my staging or production server and use `https://cdnjs.com/libraries/angular-google-analytics/1.1.8` I instead get version 1.1.7 which breaks the functionality. I'm expecting the methods `registerScriptTags()` and `registerTrackers()` to exist but they don't.

EDIT
I realised that if I fetch version 1.1.9 from cloudflare it returns version 1.1.8. So I can easily fix my problem, but the versions seem to be one step behind.

**Comment by justinsa** [comment]
Hey @origooo, I think this may have been caused by a misfired release back in 2016. See: https://github.com/revolunet/angular-google-analytics/releases. I had to publish 1.1.9 in order to correctyl publish the 1.1.8 release with all of the correct build files updated and generated. I didn't rev the number in the file since it was the 1.1.8 release code, just correctly released.

Sorry for the confusion on this one. The next time I release the version numbers will get updated so everything matches.
