### ISSUE TITLE
Extraneous page views?

### ISSUE THREAD

**Issue by stramel** [revolunet/angular-google-analytics#72]
Is this tracking duplicate pageviews when setting checkout steps?

https://github.com/revolunet/angular-google-analytics/blob/master/src/angular-google-analytics.js#L710

I don't see anything at a glance that would state there should be a page view here, https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#measuring-checkout

Shouldn't it be caught when the page changes?

**Comment by stramel** [comment]
@revolunet Bump, this is pretty important. I have no problem adding a PR for this but I just wanted to see what the reasoning behind adding the pageView track is.

**Comment by revolunet** [comment]
Looks like @justinsa added this line and i dont personally use that feature.

Justin, could you please confirm if that additional pageView is necessary or not ?

thanks

**Comment by justinsa** [comment]
That came in by @kunalkukreja in https://github.com/revolunet/angular-google-analytics/commit/841438a94fc5c1963377529d4dfea28ab89d8f2f.

The pageView call is in trackTransaction, trackRefund, and trackCheckout. I would assume they should be removed from those locations and tracking the page view should be happening separately if it needs to be called.

**Comment by revolunet** [comment]
agree. can @kunalkukreja confirm and make the change please ?

**Comment by stramel** [comment]
@revolunet @justinsa @kunalkukreja I went ahead and created a PR that removed the pageView calls pending @kunalkukreja's comment

**Comment by revolunet** [comment]
very cool thank you !

**Comment by kunalkukreja** [comment]
@stramel, @revolunet, @justinsa
  
First apology for late reply
Since transaction/checkout/refund are important events, I intentionally added these extra page view request to handle cases when user exit after these steps without visiting any other page.

Lets take a very standard use case: Suppose a user exits on Order Detail Page(successful transaction page), the track transaction call will buffer order data in _gaq and will not be used. We will lose transaction data for these cases.

Though I agree we can explicitly make these call just after trackCheckout, trackRefund, trackTransaction calls like we did for addPromo but we need to update README.md

**Comment by stramel** [comment]
@kunalkukreja 

In your use case, aren't you adding additional pageviews? Wouldn't using the `{ transport: 'beacon' }` option be a better way to handle that? I realize that would not work for older browsers.
