### ISSUE TITLE
Routing redirect causes double pageview when initially loading angular application

### ISSUE THREAD

**Issue by ArnieDude** [revolunet/angular-google-analytics#76]
This happens when the application is approached without a known path in the routing configuration and trackRoutes in enabled. So any redirects due to the use of the otherwise function of angular routing result in an extra $routeChangeSuccess, which is picked up and results in another pageview to ga.

Is this known, or is there something I might be missing in relation to the routing of angular, or is this something that would be nice to fix? :)

**Comment by rbosneag** [comment]
We had the same problem in a project, initially being very happy with lots of pageviews compared to similar periods in the past :). After reading the source code and looking for better ways to handle redirection we came up with this solution:

Instead of having `AnalyticsProvider.trackPages(true);`which records every state change including the redirects, we tracked the pages manually like this:
```javascript
$rootScope.$on("$stateChangeSuccess", function(event, currentRoute, previousRoute) {
  if (currentRoute.url !== "/live" && $state.current.name !== "main.redirect") {
    Analytics.trackPage($location.$$url);
    }
}
```
where state *main.redirect* is actually a wrapper on the *otherwise* like this:
```javascript
$stateProvider.state('main.redirect', {
        //NO URL here
        views: {
            'main.content@': {
                controller: function($rootScope) {
                    $rootScope.gotoHome = true; //or whatever you want to do
                }
            }
        }
    });
    $urlRouterProvider.otherwise(
        function($injector, $location) {
            $injector.invoke(['$state', function($state) {
                $state.transitionTo('main.redirect', {
                    "url": $location.$url
                }, {
                    location: false
                }); 
            }]);
            return $location.path();
        });
```
*On the otherwise route you can do whatever you want, here we just wanted to keep the current URL before doing the redirect from somewhere else (that's why we did `transitionTo(state, {location:false})`)*

This approach helped us avoid tracking some pages and all redirects. 
If anyone has a better solution, please share.

**Comment by stramel** [comment]
@ArnieDude @rbosneag Could you not just do the following configuration options?

```js
AnalyticsProvider.trackPages(true);
AnalyticsProvider.ignoreFirstPageLoad(true);
```

**Comment by ArnieDude** [comment]
Thats what I thought, but this only prevents the pageview fired when analytics adds the google analytics tag. 
TrackPages always sends a pageView to google analytics, regardless of when this happens, since it simply adds a listener to the $routeChangeSuccess event and triggers a pageView.

**Comment by Toxantron** [comment]
If this is still relevant I would like to take a closer look.

**Comment by Toxantron** [comment]
This might not be a global solution, but for applications using $route it will skip all those redirect routes.

**Comment by Toxantron** [comment]
I added an option to define routes in $routeProvider that shall not be tracked.  New behaviour will only track pages that define 'templateUrl' which implicitly excludes redirects as well as skipping routes that carry the 'dontTrack' property. 

Usage:
``
$routeProvider
    .when('/member/:sessionId/:memberId', {
      templateUrl : 'member.html',
      controller: 'CardController',
      pageTrack: '/member',
    })
    .otherwise({
      	templateUrl: '404.html',
      	dontTrack: true
    })
``
