### ISSUE TITLE
E-commerce does not work at all - and no support for multiple trackers

### ISSUE THREAD

**Issue by Karpo72** [revolunet/angular-google-analytics#90]
I noticed during my tests, that ecommerce data will not be send at all.

that._ecommerceEnabled() -> returns true for example on line 578
But it returns false on line 475 -> my guess is somthing with the scope is wrong.

Multiple trackers seems not to be supportet at all.

**Comment by justinsa** [comment]
Lets dig into this a bit to figure out what is expected. I notice a few things that we need to clarify to ensure we are both on the same page.

1. The recent changes that got released as version 1.0.0 do not include any changes to the ```ec``` commands to have those support multiple trackers. The changes only affected existing commands (```send``` and ```event```). It should be trivial to add multiple tracker support for those commands but additional tests should be written to cover the added cases.

2. The line numbers have changed fairly dramatically from the version you were looking at. Can you clarify what those line numbers are with the latest version? There is a distinction to be made between _ecommerceEnabled and _enhancedEcommerceEnabled. They are mutually exclusive states for the system to be in.

```javascript
       // Line 379 -> 385
        this._ecommerceEnabled = function () {
          return ecommerce && !enhancedEcommerce;
        };

        this._enhancedEcommerceEnabled = function () {
          return ecommerce && enhancedEcommerce;
        };
```

Thanks @Karpo72!

**Comment by Karpo72** [comment]
Sorry it were the line number of the dist file. in the src the line are 466 within _addTrans function. Can you explain why the function returns ecommerce && !enhancedEcommerce? That would mean you can only enable one feauture?

**Comment by Karpo72** [comment]
Regarding multi tracker: Is it not possible to sole that within the final function which sends the command? My initial idea was to keep a array of commands that support multi tracker and then decide on a final _ga function if needed to send to multiple trackers

**Comment by justinsa** [comment]
This is a behavior governed by GA. The Ecommerce Tracking documentation is explicit about ecommerce.js not being used simultaneously with ec.js. The exact statement is:

```
Important: The Ecommerce plug-in should not be used alongside the Enhanced Ecommerce (ec.js) plug-in.
```

In the case of this library, the first value to setEcommerce dictates whether any form of e-commerce tracking should be loaded and the second value indicates whether that should be enhanced e-commerce. This is notoriously confusing.

**Comment by justinsa** [comment]
Regarding this comment:

```
Regarding multi tracker: Is it not possible to solve that within the final function which sends the command? My initial idea was to keep a array of commands that support multi tracker and then decide on a final _ga function if needed to send to multiple trackers
```

Once I got into implementing it using the method proposed it became clear this was going to create a more haphazard solution for future development because the knowledge about how a command works is spread between two disparate locations in the file. All of the logic that impacts a single command should be clearly present and readable in one contiguous block. The abstraction required that each individual functions can provide a closure for evaluating trackers to include and then letting the gaMultipleTracker function handle the rest. This makes it clear that the command will use multiple trackers and any logic surrounding how those trackers are selected is identified within that function.

Enabling other commands, like 'ecommerce:addTransaction' is a fairly modest change at this point but requires thoughtful implementation because it needs to be backwards compatible so that existing usage won't change should someone upgrade the library.

**Comment by Karpo72** [comment]
Ok, regarding enhanced e-commerce and e-commerce I think the "how to" configure this module is missleading

        // Enabled eCommerce module for analytics.js (uses legacy ecommerce plugin)
        AnalyticsProvider.useECommerce(true, false);

        // Enabled enhanced eCommerce module for analytics.js (uses ec plugin instead of ecommerce plugin)
        // When enabled, legacy ecommerce plugin calls are not supported
        AnalyticsProvider.useECommerce(true, true);

**Comment by Karpo72** [comment]
Regarding multi tracker: I'm not firm with the whole history of this project, but if the events implementing the send Command already works I don't see a big risk to implement it for e-commerce too. At the end there are only three command to implement -> addTrans, addItem, commitTrans. They are working in the same way like the events except the parameters.

**Comment by justinsa** [comment]
Regarding Enhanced Ecommerce vs Ecommerce, do you have any recommendation around what would make this more clear from the perspective of the configuration function: ```useECommerce(bool, bool)```. Multiple people have run into this usability issue and it would be convenient. One change I was thinking might help is to redefine the function inputs (with backwards compatibility). For instance, instead of the ```(true, true)``` parameter values, we could use a string, which basically accomplishes a human readable enumeration. For instance: ```useECommerce('classic')``` or ```useECommerce('enhanced')```. This would at least make it explicit from the configuration standpoint that one thing is being selected instead of two. Under the covers it can continue to use the two variables, so the change is strictly limited to the setECommerce function.

Regarding multi-tracker support for ecommerce functions, I have a good idea for how to implement this, I just need to find time to do the work. Maybe I can get this done over the weekend, we'll see.

**Comment by vivekmahato26** [comment]
I am getting these errors 
1.Called method ""ec"" threw exception: TypeError: Cannot read property 'apply' of undefined
2. Plugin "ec" does not have method "addTransaction".
3. Plugin "ec" does not have method "addItem".
4.Plugin "ec" does not have method "send".
